###Get a list of all products
GET http://localhost:3000/products

### Create a product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Lenovo-1",
  "price": 8700
}

### GET a product by id
GET http://localhost:3000/products/60aa1c47ab7ab71d9cc609de

### Update a product by id
PATCH  http://localhost:3000/products/60aa1c47ab7ab71d9cc609de
Content-Type: application/json

{
  "nama":"lenovo",
  "price": 4
}


### Delete a product by id
DELETE  http://localhost:3000/products/60aa1c47ab7ab71d9cc609de



### 404 route Not Found
GET http://localhost:3000/abc_xyz


