###Get a list of all products
GET http://localhost:3000/products

### Create a product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Lenovo",
  "price": 87000
}

### GET a product by id
GET http://localhost:3000/products/60aa1c47ab7ab71d9cc609de

### Update a product by id
PATCH  http://localhost:3000/products/60aa1c47ab7ab71d9cc609de
Content-Type: application/json

{
  "nama":"lenovo",
  "price": 3
}


### Delete a product by id
DELETE  http://localhost:3000/products/60a72b427250893108e07d99



### 404 route Not Found
GET http://localhost:3000/abc_xyz


